version: '3.7'

services:
  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    volumes:
      - musicflux_db:/var/lib/mysql
    env_file:
      - .env

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

volumes:
  musicflux_db:
